# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14bt5LsVQSL6IkJLCQF5NZBzyrEjI2-_M
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt

URL = "https://www3.hkexnews.hk/sdw/search/searchsdw.aspx"
l = []
StockCode = input('StockCode:')
Start_date = input('Start_date(yyyy/mm/dd):')
End_date = input('End_date:(yyyy/mm/dd)')
with requests.Session() as s:
    s.headers={"User-Agent":"Mozilla/5.0"}
    res = s.get(URL)
    soup = BeautifulSoup(res.text,"lxml")
    payload = {item['name']:item.get('value','') for item in soup.select("input[name]")}
    payload['__EVENTTARGET'] = 'btnSearch'
    payload['txtShareholdingDate'] = End_date
    payload['txtStockCode'] = StockCode
    req = s.post(URL,data=payload,headers={"User-Agent":"Mozilla/5.0"})
    soup_obj = BeautifulSoup(req.text,"lxml")
    for items in soup_obj.select("table tbody tr"): 
        data = [item.get_text(strip=True) for item in items.select("td")]
        d = dict(s.split(':') for s in data)
        l.append(d)
        df = pd.DataFrame.from_dict(l, orient='columns')
df['Shareholding'] = df['Shareholding'].apply(lambda x: float(x.split()[0].replace(',', '')))
df['Shareholding'] = df['Shareholding'].astype(int)
df["Shareholding"].nlargest(n=10).plot(kind='hist',color = 'blue',histtype = 'bar', rwidth = 0.5,figsize=(10, 8))
plt.show()
df["Shareholding"].nlargest(n=10).plot(kind='pie',figsize=(10, 8))
plt.show()
df.nlargest(n=10, columns=['Shareholding'])

import requests
import pandas as pd
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None

URL = "https://www3.hkexnews.hk/sdw/search/searchsdw.aspx"
l = []
StockCode = input('StockCode:')
Start_date = input('Start_date(yyyy/mm/dd):')
End_date = input('End_date:(yyyy/mm/dd)')
Threshold = int(input('Threshold % of total number of shares(only integer):'))
a = pd.date_range(Start_date, End_date)
df = pd.DataFrame(columns=['Participant ID'])
for i in a:
    i = i.date().strftime("%Y/%m/%d")
    date = i
    with requests.Session() as s:
      s.headers={"User-Agent":"Mozilla/5.0"}
      res = s.get(URL)
      soup = BeautifulSoup(res.text,"lxml")
      payload = {item['name']:item.get('value','') for item in soup.select("input[name]")}
      payload['__EVENTTARGET'] = 'btnSearch'
      payload['txtShareholdingDate'] = i
      payload['txtStockCode'] = StockCode
      req = s.post(URL,data=payload,headers={"User-Agent":"Mozilla/5.0"})
      soup_obj = BeautifulSoup(req.text,"lxml")
      for items in soup_obj.select("table tbody tr"): 
         data = [item.get_text(strip=True) for item in items.select("td")]
         d = dict(s.split(':') for s in data)
         l.append(d)
         i = pd.DataFrame.from_dict(l, orient='columns')
         i = i[['Participant ID', 'Shareholding']]
         i.rename(columns = {'Shareholding': date}, inplace = True)
    df = pd.concat([df, i])

for column in df:
  df[column] = df[column].str.replace(',', '')
df=df.fillna(0)
cols = df.columns
df[cols[1:]] = df[cols[1:]].apply(pd.to_numeric, errors='coerce')
df_t = df.transpose()
df2 = df_t.iloc[1: , :]
df_header =  df_t.iloc[:1 ]
df3=df2.pct_change()
all_dfs = [df_header, df3]
df4=pd.concat(all_dfs)
df4=df4.transpose()
col = df4.columns
df4[col[1:]] = df4[col[1:]].apply(pd.to_numeric, errors='coerce')
df4=df4.fillna(0.0)
df5=df4.drop(['Participant ID'], axis=1)
Threshold=0.01*Threshold
T2=-1*Threshold
for column in df5:
  df5.loc[(df5[column]>=Threshold) | (df5[column]<=T2) , column] = "Value is greater than threshold"

df5['Participant ID']= df4['Participant ID']
print(df5)

